-- ============================================================
-- Flowable 工作流模块数据库表结构
-- ============================================================

-- 流程定义表
CREATE TABLE IF NOT EXISTS `workflow_definition` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `process_key` VARCHAR(100) NOT NULL COMMENT '流程定义Key',
    `process_name` VARCHAR(200) NOT NULL COMMENT '流程名称',
    `category` VARCHAR(100) DEFAULT NULL COMMENT '流程分类',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '流程描述',
    `model_xml` LONGTEXT COMMENT '流程模型XML内容',
    `diagram_svg` LONGTEXT COMMENT '流程图SVG',
    `version` INT DEFAULT 1 COMMENT '流程版本',
    `status` TINYINT DEFAULT 0 COMMENT '状态（0:草稿 1:已发布 2:已停用）',
    `form_type` TINYINT DEFAULT 0 COMMENT '表单类型（0:自定义表单 1:在线表单）',
    `form_id` BIGINT DEFAULT NULL COMMENT '表单ID',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `is_multi_instance` TINYINT DEFAULT 0 COMMENT '是否多实例（0:否 1:是）',
    `timeout_remind` INT DEFAULT 0 COMMENT '超时提醒设置（小时）',
    `icon` VARCHAR(200) DEFAULT NULL COMMENT '流程图标',
    `sort_order` INT DEFAULT 0 COMMENT '排序号',
    `flowable_definition_id` VARCHAR(100) DEFAULT NULL COMMENT 'Flowable流程定义ID',
    `deployment_id` VARCHAR(100) DEFAULT NULL COMMENT '部署ID',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_process_key` (`process_key`),
    KEY `idx_status` (`status`),
    KEY `idx_tenant_id` (`tenant_id`),
    KEY `idx_flowable_definition_id` (`flowable_definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程定义表';

-- 流程实例表
CREATE TABLE IF NOT EXISTS `workflow_instance` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `definition_id` BIGINT NOT NULL COMMENT '流程定义ID',
    `process_instance_id` VARCHAR(100) NOT NULL COMMENT 'Flowable流程实例ID',
    `business_type` VARCHAR(100) DEFAULT NULL COMMENT '业务类型',
    `business_key` VARCHAR(200) DEFAULT NULL COMMENT '业务Key',
    `business_title` VARCHAR(500) DEFAULT NULL COMMENT '业务标题',
    `applicant_id` BIGINT NOT NULL COMMENT '申请人ID',
    `applicant_name` VARCHAR(100) DEFAULT NULL COMMENT '申请人姓名',
    `dept_id` BIGINT DEFAULT NULL COMMENT '申请人部门ID',
    `dept_name` VARCHAR(100) DEFAULT NULL COMMENT '申请人部门名称',
    `status` TINYINT DEFAULT 0 COMMENT '流程状态（0:运行中 1:已完成 2:已终止 3:已挂起）',
    `result` TINYINT DEFAULT 0 COMMENT '流程结果（0:审批中 1:通过 2:驳回 3:撤回）',
    `start_time` DATETIME DEFAULT NULL COMMENT '开始时间',
    `end_time` DATETIME DEFAULT NULL COMMENT '结束时间',
    `duration` BIGINT DEFAULT NULL COMMENT '持续时间（毫秒）',
    `current_node_id` VARCHAR(100) DEFAULT NULL COMMENT '当前节点ID',
    `current_node_name` VARCHAR(200) DEFAULT NULL COMMENT '当前节点名称',
    `current_assignee_id` BIGINT DEFAULT NULL COMMENT '当前处理人ID',
    `current_assignee_name` VARCHAR(100) DEFAULT NULL COMMENT '当前处理人姓名',
    `form_data` JSON DEFAULT NULL COMMENT '表单数据JSON',
    `variables` JSON DEFAULT NULL COMMENT '流程变量JSON',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_definition_id` (`definition_id`),
    KEY `idx_process_instance_id` (`process_instance_id`),
    KEY `idx_business_key` (`business_key`),
    KEY `idx_applicant_id` (`applicant_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tenant_id` (`tenant_id`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例表';

-- 流程任务表
CREATE TABLE IF NOT EXISTS `workflow_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `instance_id` BIGINT NOT NULL COMMENT '流程实例ID',
    `task_id` VARCHAR(100) NOT NULL COMMENT 'Flowable任务ID',
    `definition_id` BIGINT DEFAULT NULL COMMENT '流程定义ID',
    `node_id` VARCHAR(100) DEFAULT NULL COMMENT '节点ID',
    `node_name` VARCHAR(200) DEFAULT NULL COMMENT '节点名称',
    `task_type` TINYINT DEFAULT 0 COMMENT '任务类型（0:审批任务 1:抄送任务 2:办理任务）',
    `assignee_id` BIGINT DEFAULT NULL COMMENT '处理人ID',
    `assignee_name` VARCHAR(100) DEFAULT NULL COMMENT '处理人姓名',
    `candidate_ids` VARCHAR(500) DEFAULT NULL COMMENT '候选人ID列表（逗号分隔）',
    `candidate_groups` VARCHAR(500) DEFAULT NULL COMMENT '候选组',
    `status` TINYINT DEFAULT 0 COMMENT '任务状态（0:待处理 1:已处理 2:已转办 3:已委派）',
    `result` TINYINT DEFAULT 0 COMMENT '审批结果（0:待审批 1:通过 2:驳回 3:转办 4:委派 5:撤回）',
    `comment` VARCHAR(1000) DEFAULT NULL COMMENT '审批意见',
    `form_data` JSON DEFAULT NULL COMMENT '表单数据JSON',
    `arrive_time` DATETIME DEFAULT NULL COMMENT '到达时间',
    `handle_time` DATETIME DEFAULT NULL COMMENT '处理时间',
    `duration` BIGINT DEFAULT NULL COMMENT '持续时间（毫秒）',
    `due_time` DATETIME DEFAULT NULL COMMENT '超时时间',
    `is_read` TINYINT DEFAULT 0 COMMENT '是否已读（0:未读 1:已读）',
    `read_time` DATETIME DEFAULT NULL COMMENT '阅读时间',
    `parent_task_id` BIGINT DEFAULT NULL COMMENT '父任务ID',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_instance_id` (`instance_id`),
    KEY `idx_task_id` (`task_id`),
    KEY `idx_assignee_id` (`assignee_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tenant_id` (`tenant_id`),
    KEY `idx_arrive_time` (`arrive_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程任务表';

-- 流程历史记录表
CREATE TABLE IF NOT EXISTS `workflow_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `instance_id` BIGINT NOT NULL COMMENT '流程实例ID',
    `task_id` BIGINT DEFAULT NULL COMMENT '任务ID',
    `node_id` VARCHAR(100) DEFAULT NULL COMMENT '节点ID',
    `node_name` VARCHAR(200) DEFAULT NULL COMMENT '节点名称',
    `operation_type` TINYINT DEFAULT NULL COMMENT '操作类型（1:提交 2:审批通过 3:审批驳回 4:转办 5:委派 6:撤回 7:终止 8:抄送 9:评论）',
    `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
    `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作人姓名',
    `operator_dept` VARCHAR(100) DEFAULT NULL COMMENT '操作人部门',
    `comment` VARCHAR(1000) DEFAULT NULL COMMENT '操作意见',
    `result` TINYINT DEFAULT NULL COMMENT '审批结果（1:通过 2:驳回）',
    `form_data` JSON DEFAULT NULL COMMENT '表单数据JSON',
    `variables` JSON DEFAULT NULL COMMENT '流程变量JSON',
    `attachments` JSON DEFAULT NULL COMMENT '附件列表JSON',
    `operation_time` DATETIME DEFAULT NULL COMMENT '操作时间',
    `duration` BIGINT DEFAULT NULL COMMENT '持续时间（毫秒）',
    `target_node_id` VARCHAR(100) DEFAULT NULL COMMENT '目标节点ID',
    `target_node_name` VARCHAR(200) DEFAULT NULL COMMENT '目标节点名称',
    `target_assignee_id` BIGINT DEFAULT NULL COMMENT '目标处理人ID',
    `target_assignee_name` VARCHAR(100) DEFAULT NULL COMMENT '目标处理人姓名',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `ip_address` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_instance_id` (`instance_id`),
    KEY `idx_task_id` (`task_id`),
    KEY `idx_operator_id` (`operator_id`),
    KEY `idx_operation_type` (`operation_type`),
    KEY `idx_operation_time` (`operation_time`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程历史记录表';

-- 流程表单表
CREATE TABLE IF NOT EXISTS `workflow_form` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `form_name` VARCHAR(200) NOT NULL COMMENT '表单名称',
    `form_code` VARCHAR(100) NOT NULL COMMENT '表单编码',
    `category` VARCHAR(100) DEFAULT NULL COMMENT '表单分类',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '表单描述',
    `form_config` JSON DEFAULT NULL COMMENT '表单JSON配置',
    `field_config` JSON DEFAULT NULL COMMENT '表单字段配置JSON',
    `status` TINYINT DEFAULT 0 COMMENT '状态（0:草稿 1:已发布 2:已停用）',
    `version` INT DEFAULT 1 COMMENT '版本号',
    `is_default` TINYINT DEFAULT 0 COMMENT '是否默认表单（0:否 1:是）',
    `icon` VARCHAR(200) DEFAULT NULL COMMENT '图标',
    `sort_order` INT DEFAULT 0 COMMENT '排序号',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_form_code` (`form_code`),
    KEY `idx_category` (`category`),
    KEY `idx_status` (`status`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程表单表';

-- 流程节点配置表
CREATE TABLE IF NOT EXISTS `workflow_node_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `definition_id` BIGINT NOT NULL COMMENT '流程定义ID',
    `node_id` VARCHAR(100) NOT NULL COMMENT '节点ID',
    `node_name` VARCHAR(200) DEFAULT NULL COMMENT '节点名称',
    `node_type` VARCHAR(50) DEFAULT NULL COMMENT '节点类型',
    `assignee_type` TINYINT DEFAULT NULL COMMENT '审批人类型（1:指定用户 2:指定角色 3:部门负责人 4:发起人自选 5:连续多级主管 6:发起人自己）',
    `assignee_ids` VARCHAR(500) DEFAULT NULL COMMENT '审批人IDs（逗号分隔）',
    `role_ids` VARCHAR(500) DEFAULT NULL COMMENT '审批角色IDs',
    `dept_level` INT DEFAULT NULL COMMENT '部门级别',
    `multi_approve_type` TINYINT DEFAULT 1 COMMENT '多人审批方式（1:会签 2:或签 3:依次审批）',
    `pass_rate` INT DEFAULT 100 COMMENT '审批通过比例',
    `allow_transfer` TINYINT DEFAULT 1 COMMENT '是否允许转办（0:否 1:是）',
    `allow_delegate` TINYINT DEFAULT 1 COMMENT '是否允许委派（0:否 1:是）',
    `allow_add_sign` TINYINT DEFAULT 0 COMMENT '是否允许加签（0:否 1:是）',
    `allow_back` TINYINT DEFAULT 1 COMMENT '是否允许退回（0:否 1:是）',
    `back_type` TINYINT DEFAULT 1 COMMENT '退回方式（1:退回上一步 2:退回发起人 3:自由选择）',
    `require_comment` TINYINT DEFAULT 0 COMMENT '是否必填意见（0:否 1:是）',
    `allow_cc` TINYINT DEFAULT 1 COMMENT '是否允许抄送（0:否 1:是）',
    `cc_user_ids` VARCHAR(500) DEFAULT NULL COMMENT '抄送人IDs',
    `timeout_hours` INT DEFAULT 0 COMMENT '超时提醒设置（小时）',
    `form_permissions` JSON DEFAULT NULL COMMENT '表单权限配置JSON',
    `button_permissions` JSON DEFAULT NULL COMMENT '按钮权限配置JSON',
    `condition_expression` VARCHAR(500) DEFAULT NULL COMMENT '条件表达式',
    `sort_order` INT DEFAULT 0 COMMENT '排序号',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_definition_id` (`definition_id`),
    KEY `idx_node_id` (`node_id`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程节点配置表';

-- 流程回调记录表
CREATE TABLE IF NOT EXISTS `workflow_callback` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `instance_id` BIGINT NOT NULL COMMENT '流程实例ID',
    `business_type` VARCHAR(100) DEFAULT NULL COMMENT '业务类型',
    `business_key` VARCHAR(200) DEFAULT NULL COMMENT '业务Key',
    `callback_type` TINYINT NOT NULL COMMENT '回调类型（1:流程开始 2:流程结束 3:节点进入 4:节点完成 5:任务分配 6:审批结果）',
    `callback_url` VARCHAR(500) DEFAULT NULL COMMENT '回调URL',
    `callback_data` JSON DEFAULT NULL COMMENT '回调数据JSON',
    `status` TINYINT DEFAULT 0 COMMENT '回调状态（0:待发送 1:发送成功 2:发送失败）',
    `retry_count` INT DEFAULT 0 COMMENT '发送次数',
    `max_retry` INT DEFAULT 3 COMMENT '最大重试次数',
    `response_result` TEXT DEFAULT NULL COMMENT '响应结果',
    `send_time` DATETIME DEFAULT NULL COMMENT '发送时间',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_instance_id` (`instance_id`),
    KEY `idx_callback_type` (`callback_type`),
    KEY `idx_status` (`status`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程回调记录表';

-- 流程抄送记录表
CREATE TABLE IF NOT EXISTS `workflow_carbon_copy` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `instance_id` BIGINT NOT NULL COMMENT '流程实例ID',
    `task_id` BIGINT DEFAULT NULL COMMENT '任务ID',
    `node_id` VARCHAR(100) DEFAULT NULL COMMENT '节点ID',
    `node_name` VARCHAR(200) DEFAULT NULL COMMENT '节点名称',
    `cc_user_id` BIGINT NOT NULL COMMENT '抄送人ID',
    `cc_user_name` VARCHAR(100) DEFAULT NULL COMMENT '抄送人姓名',
    `is_read` TINYINT DEFAULT 0 COMMENT '是否已读（0:未读 1:已读）',
    `read_time` DATETIME DEFAULT NULL COMMENT '阅读时间',
    `cc_time` DATETIME DEFAULT NULL COMMENT '抄送时间',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '抄送原因/备注',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标志（0:未删除 1:已删除）',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_instance_id` (`instance_id`),
    KEY `idx_cc_user_id` (`cc_user_id`),
    KEY `idx_is_read` (`is_read`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程抄送记录表';
